### ISSUE TITLE
Change space-before-function-paren 

### ISSUE THREAD

**Issue by SindreSvendby** [dbmedialab/ts-config-aller#2]
### Current setting:

`'space-before-function-paren': [ true, 'always' ]`

###  Rule info:
https://palantir.github.io/tslint/rules/space-before-function-paren/

### New suggestion
"space-before-function-paren": [true, {"anonymous": "always", "named": "never", "asyncArrow": "always"}]

### Benefits
My problem with this setting always to true is that it enforces this on named functions there are some plugins that I used that ended up with a race condition, so on each save it swapped between what tslint wanted and want the other plugin wanted. To get tools that work together well is important for me, the  syntax i do not really care about as long as it is consistent. 

### Drawbacks
 * Project that depends on it will need to fix it, but it's only one commit since this has a fixer (see palantir link)
* I think some would argue that you have different rules between named, anonymous and async. and that is a drawback in it self.

**Comment by egreb** [comment]
The committee had an meeting this morning about this. We would like to map how many of us that is actually using vscode and prettier (which I assume is the extension that has issues/conflicts with eslint?), before we make an decision.
In either case, we want to have space/no space on all the different functions calls, not only before named functions.
